---

name: Test vutils-yaml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'

    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox

      - name: Run tox
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          PYVER=${COVERALLS_FLAG_NAME}
          BASEDIR=.tox/py${PYVER//.}/lib/python${PYVER}/site-packages/
          export COVERALLS_CMD="coveralls --basedir=${BASEDIR} --srcdir=src"
          tox -e py${PYVER//.}
          if test 0${PYVER##*.} -ge 9; then
            tox -e linters
          fi

  finish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install coveralls

      - name: Notify coveralls.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
        run: |
          coveralls --finish
